-- CameraManager (ModuleScript) - ВЕРСИЯ 3.0 (Синхронизированная)
local TweenService = game:GetService("TweenService")
local Workspace = game:GetService("Workspace")
local CameraManager = {}

local isAnimating = false
local isCameraTweening = false
local currentSlotInView = nil
local animationTracks = {}

local CAMERA_START_CFRAME = CFrame.new(29.938, -27.269, -31.038) * CFrame.Angles(math.rad(0.9), math.rad(-0.257), math.rad(0))
local CAMERA_CHARACTER_CFRAME = CFrame.new(31.415, -29.366, -47.602) * CFrame.Angles(math.rad(3.439), math.rad(-1.76), math.rad(0))
local EDITOR_CAMERA_CFRAMES = {[1] = CFrame.new(29.117, -27.982, -55.142) * CFrame.Angles(math.rad(-5.101), math.rad(1.602), math.rad(-0)),[2] = CFrame.new(14.854, -28.362, -55.928) * CFrame.Angles(math.rad(-3.9), math.rad(1.601), math.rad(0)),[3] = CFrame.new(45.306, -28.381, -56.144) * CFrame.Angles(math.rad(-4.2), math.rad(6.402), math.rad(0))}
local currentCameraTarget = CAMERA_START_CFRAME

local UI, Sounds, Player, StarterGui, PlayerActionsEvent, PlayerGui
local RedactorZone = Workspace.Menu.Theater:WaitForChild("RedactorZone")

local function fadeSlotLight(slotIndex,fadeIn,duration) local lightModel=Workspace.Menu.Theater:FindFirstChild("SvetSlot"..slotIndex) if not lightModel then return end local tweenInfo=TweenInfo.new(duration) for _,child in ipairs(lightModel:GetDescendants()) do if child:IsA("SpotLight") then child.Enabled=true local targetBrightness=fadeIn and 6 or 0 TweenService:Create(child,tweenInfo,{Brightness=targetBrightness}):Play() end end end
local function fadeMainLights(fadeIn,duration) local lightsFolder=Workspace:FindFirstChild("MenuLights") if not lightsFolder then return end local tweenInfo=TweenInfo.new(duration,Enum.EasingStyle.Sine) for _,lightSource in ipairs(lightsFolder:GetChildren()) do for _,child in ipairs(lightSource:GetDescendants()) do if child:IsA("Light") then child.Enabled=true local targetBrightness=fadeIn and 6 or 0 TweenService:Create(child,tweenInfo,{Brightness=targetBrightness}):Play() end end end end

function CameraManager.InitLights() fadeMainLights(false,0) for i=1,3 do fadeSlotLight(i,false,0) end RedactorZone.Transparency=1 end
function CameraManager.Init(_UI,_Sounds,_Player,_StarterGui,_PlayerActionsEvent,_PlayerGui) UI,Sounds,Player,StarterGui,PlayerActionsEvent,PlayerGui=_UI,_Sounds,_Player,_StarterGui,_PlayerActionsEvent,_PlayerGui end
function CameraManager.RegisterAnimationTrack(slotIndex,track) animationTracks[slotIndex]=track end
function CameraManager.GetCurrentCameraTarget() return currentCameraTarget end
function CameraManager.IsCameraTweening() return isCameraTweening end
function CameraManager.IsAnimating() return isAnimating end

function CameraManager.TransitionToMainMenu(isLoadingRef) if not isLoadingRef.Value then return end isLoadingRef.Value=false UI.Menu.loadingCanvas.Visible=false Sounds.LightSwitchOn:Play() fadeMainLights(true,0) Sounds.AmbientMusic1:Play() Sounds.AmbientMusic2:Play() UI.Menu.mainMenuCanvas.Visible=true UI.Menu.mainMenuCanvas.GroupTransparency=1 TweenService:Create(UI.Menu.mainMenuCanvas,TweenInfo.new(1.0),{GroupTransparency=0}):Play() end
function CameraManager.TransitionToCharacterSelect() if isAnimating then return end; isAnimating=true local cameraMoveDuration=2.0 fadeMainLights(false,cameraMoveDuration) local theaterModel=Workspace:FindFirstChild("MenuScene") local LeftCurtain,RightCurtain=theaterModel:FindFirstChild("LeftCurtain"),theaterModel:FindFirstChild("RightCurtain") if not LeftCurtain or not RightCurtain then isAnimating=false;return end TweenService:Create(UI.Menu.mainMenuCanvas,TweenInfo.new(0.5),{GroupTransparency=1}):Play() task.wait(0.5) UI.Menu.mainMenuCanvas.Visible=false Sounds.CurtainOpen:Play() local curtainInfo=TweenInfo.new(1.5,Enum.EasingStyle.Sine,Enum.EasingDirection.InOut) TweenService:Create(LeftCurtain,curtainInfo,{Position=Vector3.new(5.5,-27.024,-52.261)}):Play() TweenService:Create(RightCurtain,curtainInfo,{Position=Vector3.new(58.5,-27.024,-52.261)}):Play() local cameraInfo=TweenInfo.new(cameraMoveDuration,Enum.EasingStyle.Sine,Enum.EasingDirection.InOut) local tweenCamera=TweenService:Create(Workspace.CurrentCamera,cameraInfo,{CFrame=CAMERA_CHARACTER_CFRAME}) isCameraTweening=true; tweenCamera:Play() tweenCamera.Completed:Connect(function() currentCameraTarget=CAMERA_CHARACTER_CFRAME isCameraTweening=false; isAnimating=false UI.Menu.characterSelectCanvas.Visible=true; UI.Menu.characterSelectCanvas.GroupTransparency=1 TweenService:Create(UI.Menu.characterSelectCanvas,TweenInfo.new(1.0),{GroupTransparency=0}):Play() end) end

function CameraManager.StartGame(slotIndex) if isAnimating then return end; isAnimating=true Sounds.StartGameClick:Play() for i=1,3 do if UI.Menu.slotUI[i] and UI.Menu.slotUI[i].ButtonContainer then UI.Menu.slotUI[i].ButtonContainer.Visible=false end end local fadeInfo=TweenInfo.new(1.5) TweenService:Create(Sounds.AmbientMusic1,fadeInfo,{Volume=0}):Play() TweenService:Create(Sounds.AmbientMusic2,fadeInfo,{Volume=0}):Play() local fadeOutTween=TweenService:Create(UI.Menu.fadeFrame,fadeInfo,{BackgroundTransparency=0}) fadeOutTween:Play(); fadeOutTween.Completed:Wait() local playerStatsUI=PlayerGui:FindFirstChild("PlayerStatsUI") if playerStatsUI then playerStatsUI.Enabled=true end PlayerActionsEvent:FireServer("RequestCharacterLoad",slotIndex) UI.Menu.menuScreenGui:Destroy() end

function CameraManager.TransitionToEditor(slotIndex) if isAnimating then return end; isAnimating=true; currentSlotInView=slotIndex local cameraMoveDuration=1.5 UI.Menu.characterSelectCanvas.Visible=false local cameraTween=TweenService:Create(Workspace.CurrentCamera,TweenInfo.new(cameraMoveDuration,Enum.EasingStyle.Sine,Enum.EasingDirection.InOut),{CFrame=EDITOR_CAMERA_CFRAMES[slotIndex]}) cameraTween:Play() fadeSlotLight(slotIndex,true,cameraMoveDuration) if animationTracks[slotIndex] then animationTracks[slotIndex]:Stop(0.5) end TweenService:Create(RedactorZone,TweenInfo.new(cameraMoveDuration),{Transparency=0}):Play() isCameraTweening=true cameraTween.Completed:Connect(function() currentCameraTarget=EDITOR_CAMERA_CFRAMES[slotIndex]; isCameraTweening=false UI.Menu.editorCanvas.Visible=true; UI.Menu.editorCanvas.GroupTransparency=0 local panelTween=TweenService:Create(UI.Menu.editorPanel,TweenInfo.new(0.8,Enum.EasingStyle.Quint,Enum.EasingDirection.Out),{Position=UDim2.new(0.015,0,0.025,0)}) panelTween:Play() panelTween.Completed:Connect(function() isAnimating=false end) end) end
function CameraManager.TransitionFromEditor() if isAnimating or not currentSlotInView then return end; isAnimating=true local cameraMoveDuration=1.5 if animationTracks[currentSlotInView] then animationTracks[currentSlotInView]:Play(0.5) end TweenService:Create(RedactorZone,TweenInfo.new(cameraMoveDuration),{Transparency=1}):Play() local panelTween=TweenService:Create(UI.Menu.editorPanel,TweenInfo.new(0.8,Enum.EasingStyle.Quint,Enum.EasingDirection.In),{Position=UDim2.new(0,-UI.Menu.editorPanel.AbsoluteSize.X,0.025,0)}) panelTween:Play() panelTween.Completed:Connect(function() UI.Menu.editorCanvas.Visible=false local cameraTween=TweenService:Create(Workspace.CurrentCamera,TweenInfo.new(cameraMoveDuration,Enum.EasingStyle.Sine,Enum.EasingDirection.InOut),{CFrame=CAMERA_CHARACTER_CFRAME}) cameraTween:Play() fadeSlotLight(currentSlotInView,false,cameraMoveDuration) isCameraTweening=true cameraTween.Completed:Connect(function() UI.Menu.characterSelectCanvas.Visible=true TweenService:Create(UI.Menu.characterSelectCanvas,TweenInfo.new(0.5),{GroupTransparency=0}):Play() isCameraTweening=false currentCameraTarget=CAMERA_CHARACTER_CFRAME currentSlotInView=nil; isAnimating=false end) end) end

return CameraManager